import getHomeLiveEvents from '../data/getHomeLiveEvents.json';

export const liveDetailDataSlice = {
  '6744932314': {
    ResultInfo: 'Ha comenzado a las 06:33 6-3  2-2  (30-0)',
    DefaultGame: null,
    liveData: {
      Sets: [
        [6, 3],
        [2, 2],
      ],
      HomeService: false,
      SetsHome: 1,
      SetsAway: 0,
      ParticipantHome: 'Renta Tokuda',
      ParticipantAway: 'Rubin Statham',
      Period: 16,
      PeriodName: '2º Set',
      Actions: [
        {
          Period: 15,
          PeriodName: '1º Set',
          Time: 0,
          ActionType: 14,
          ActionTypeName: 'Patada inicial',
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: true,
        },
      ],
      ResultHome: 30,
      ResultAway: 0,
      Time: '06:33',
      MatchTime: -1,
      RemainingPeriodTime: '',
    },
    StartDate: '/Date(1683520380000)/',
    StarDate: '/Date(1683520380000)/',
    isLive: true,
    LeagueName: 'ATP Challenger Busan - Clasificación',
    ChildrenCount: 26,
    SportName: 'Tenis',
    CountryCode: 'ATPCHQ',
    CountryName: 'ATP Challenger Clasificación',
    Participants: [
      {
        ExtensionData: {},
        AdditionalValues: {
          KeyValues: [],
          LocalizedValues: [
            {
              Key: 'ParticipantOrder',
              Value: '0',
            },
          ],
          ExtensionData: {},
          ReferenceId: 0,
        },
        Id: 14805764,
        IsHome: true,
        LocalizedNames: {
          LocalizedValues: [
            {
              ExtensionData: {},
              CountryCode: '-1',
              LanguageCode: '-1',
              Value: 'Renta Tokuda',
            },
          ],
          ExtensionData: {},
          ReferenceId: -1,
        },
        LocalizedShortNames: {
          LocalizedValues: [
            {
              ExtensionData: {},
              CountryCode: '-1',
              LanguageCode: '-1',
              Value: 'RTo',
            },
          ],
          ExtensionData: {},
          ReferenceId: 0,
        },
      },
      {
        ExtensionData: {},
        AdditionalValues: {
          KeyValues: [],
          LocalizedValues: [
            {
              Key: 'ParticipantOrder',
              Value: '1',
            },
          ],
          ExtensionData: {},
          ReferenceId: 0,
        },
        Id: 17015545,
        IsHome: false,
        LocalizedNames: {
          LocalizedValues: [
            {
              ExtensionData: {},
              CountryCode: '-1',
              LanguageCode: '-1',
              Value: 'Rubin Statham',
            },
          ],
          ExtensionData: {},
          ReferenceId: -1,
        },
        LocalizedShortNames: {
          LocalizedValues: [
            {
              ExtensionData: {},
              CountryCode: '-1',
              LanguageCode: '-1',
              Value: 'RSt',
            },
          ],
          ExtensionData: {},
          ReferenceId: 0,
        },
      },
    ],
    LiveHistory: null,
    SmartMarketReferenceGameTypeIds: '',
    StatisticsId: '41116015',
    SportId: '2819846742',
    Games: [
      {
        Results: [
          {
            Odd: 1.3,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224409758',
            GameTypeId: 978,
            GameSpecialOddsValue: '<Set>2|<Game>5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'No',
            NodeId: '7224409763',
            ParentNodeId: '7224409758',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 3.2,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224409758',
            GameTypeId: 978,
            GameSpecialOddsValue: '<Set>2|<Game>5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Si',
            NodeId: '7224409762',
            ParentNodeId: '7224409758',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonline',
        CategoryInfo: {
          CategoryId: '95',
          CategoryName: 'JUEGOS',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '95',
            CategoryName: 'JUEGOS',
            IsRelevant: true,
          },
        ],
        GameType: 978,
        SmartMarketAvailable: false,
        Spov: '<Set>2|<Game>5',
        Name: '¿Habrá un 40 iguales en el Juego 5 del Set 2?',
        NodeId: '7224409758',
        ParentNodeId: '7219795979',
        Priority: 9275,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 3.2,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224418966',
            GameTypeId: 978,
            GameSpecialOddsValue: '<Set>2|<Game>6',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Si',
            NodeId: '7224418972',
            ParentNodeId: '7224418966',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 1.3,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224418966',
            GameTypeId: 978,
            GameSpecialOddsValue: '<Set>2|<Game>6',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'No',
            NodeId: '7224418973',
            ParentNodeId: '7224418966',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonline',
        CategoryInfo: {
          CategoryId: '95',
          CategoryName: 'JUEGOS',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '95',
            CategoryName: 'JUEGOS',
            IsRelevant: true,
          },
        ],
        GameType: 978,
        SmartMarketAvailable: false,
        Spov: '<Set>2|<Game>6',
        Name: '¿Habrá un 40 iguales en el Juego 6 del Set 2?',
        NodeId: '7224418966',
        ParentNodeId: '7219795979',
        Priority: 9275,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 2.55,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224409759',
            GameTypeId: 1636,
            GameSpecialOddsValue: '<Set>2|<Game>5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham',
            NodeId: '7224409765',
            ParentNodeId: '7224409759',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 1.45,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224409759',
            GameTypeId: 1636,
            GameSpecialOddsValue: '<Set>2|<Game>5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda',
            NodeId: '7224409764',
            ParentNodeId: '7224409759',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonline',
        CategoryInfo: {
          CategoryId: '99',
          CategoryName: 'PRINCIPALES',
          IsRelevant: false,
        },
        CategoryInfos: [
          {
            CategoryId: '99',
            CategoryName: 'PRINCIPALES',
            IsRelevant: true,
          },
          {
            CategoryId: '95',
            CategoryName: 'JUEGOS',
            IsRelevant: true,
          },
        ],
        GameType: 1636,
        SmartMarketAvailable: false,
        Spov: '<Set>2|<Game>5',
        Name: 'Ganador del juego (Juego 5 / Set 2)',
        NodeId: '7224409759',
        ParentNodeId: '7219795979',
        Priority: 9350,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 1.22,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224418965',
            GameTypeId: 1636,
            GameSpecialOddsValue: '<Set>2|<Game>6',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda',
            NodeId: '7224418970',
            ParentNodeId: '7224418965',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 3.8,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224418965',
            GameTypeId: 1636,
            GameSpecialOddsValue: '<Set>2|<Game>6',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham',
            NodeId: '7224418971',
            ParentNodeId: '7224418965',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonline',
        CategoryInfo: {
          CategoryId: '99',
          CategoryName: 'PRINCIPALES',
          IsRelevant: false,
        },
        CategoryInfos: [
          {
            CategoryId: '99',
            CategoryName: 'PRINCIPALES',
            IsRelevant: true,
          },
          {
            CategoryId: '95',
            CategoryName: 'JUEGOS',
            IsRelevant: true,
          },
        ],
        GameType: 1636,
        SmartMarketAvailable: false,
        Spov: '<Set>2|<Game>6',
        Name: 'Ganador del juego (Juego 6 / Set 2)',
        NodeId: '7224418965',
        ParentNodeId: '7219795979',
        Priority: 9350,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 1.13,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7219795996',
            GameTypeId: 97,
            GameSpecialOddsValue: '',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda',
            NodeId: '7219795997',
            ParentNodeId: '7219795996',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 5,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7219795996',
            GameTypeId: 97,
            GameSpecialOddsValue: '',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham',
            NodeId: '7219795998',
            ParentNodeId: '7219795996',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonline',
        CategoryInfo: {
          CategoryId: '99',
          CategoryName: 'PRINCIPALES',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '99',
            CategoryName: 'PRINCIPALES',
            IsRelevant: true,
          },
        ],
        GameType: 97,
        SmartMarketAvailable: false,
        Spov: '',
        Name: 'Ganador del partido',
        NodeId: '7219795996',
        ParentNodeId: '7219795979',
        Priority: 9500,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 2.3,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224418503',
            GameTypeId: 1972,
            GameSpecialOddsValue: '<Set>2|<Game>5|<Point>2',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda',
            NodeId: '7224418514',
            ParentNodeId: '7224418503',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 1.55,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224418503',
            GameTypeId: 1972,
            GameSpecialOddsValue: '<Set>2|<Game>5|<Point>2',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham',
            NodeId: '7224418515',
            ParentNodeId: '7224418503',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonlist',
        CategoryInfo: {
          CategoryId: '99',
          CategoryName: 'PRINCIPALES',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '99',
            CategoryName: 'PRINCIPALES',
            IsRelevant: true,
          },
        ],
        GameType: 1972,
        SmartMarketAvailable: false,
        Spov: '<Set>2|<Game>5|<Point>2',
        Name: 'Ganador del Punto 2 en el Juego 5 del Set 2',
        NodeId: '7224418503',
        ParentNodeId: '7219795979',
        Priority: 9480,
        SportHandle: 'tennis',
        Locked: true,
      },
      {
        Results: [
          {
            Odd: 1.6,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224419001',
            GameTypeId: 1972,
            GameSpecialOddsValue: '<Set>2|<Game>5|<Point>3',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham',
            NodeId: '7224419003',
            ParentNodeId: '7224419001',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 2.2,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224419001',
            GameTypeId: 1972,
            GameSpecialOddsValue: '<Set>2|<Game>5|<Point>3',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda',
            NodeId: '7224419002',
            ParentNodeId: '7224419001',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonlist',
        CategoryInfo: {
          CategoryId: '99',
          CategoryName: 'PRINCIPALES',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '99',
            CategoryName: 'PRINCIPALES',
            IsRelevant: true,
          },
        ],
        GameType: 1972,
        SmartMarketAvailable: false,
        Spov: '<Set>2|<Game>5|<Point>3',
        Name: 'Ganador del Punto 3 en el Juego 5 del Set 2',
        NodeId: '7224419001',
        ParentNodeId: '7219795979',
        Priority: 9480,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 1.6,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224419838',
            GameTypeId: 1972,
            GameSpecialOddsValue: '<Set>2|<Game>5|<Point>4',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham',
            NodeId: '7224419840',
            ParentNodeId: '7224419838',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 2.2,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224419838',
            GameTypeId: 1972,
            GameSpecialOddsValue: '<Set>2|<Game>5|<Point>4',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda',
            NodeId: '7224419839',
            ParentNodeId: '7224419838',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonlist',
        CategoryInfo: {
          CategoryId: '99',
          CategoryName: 'PRINCIPALES',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '99',
            CategoryName: 'PRINCIPALES',
            IsRelevant: true,
          },
        ],
        GameType: 1972,
        SmartMarketAvailable: false,
        Spov: '<Set>2|<Game>5|<Point>4',
        Name: 'Ganador del Punto 4 en el Juego 5 del Set 2',
        NodeId: '7224419838',
        ParentNodeId: '7219795979',
        Priority: 9480,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 2.95,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7223674126',
            GameTypeId: 262,
            GameSpecialOddsValue: '<Set>2',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham',
            NodeId: '7223674132',
            ParentNodeId: '7223674126',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 1.35,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7223674126',
            GameTypeId: 262,
            GameSpecialOddsValue: '<Set>2',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda',
            NodeId: '7223674131',
            ParentNodeId: '7223674126',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonline',
        CategoryInfo: {
          CategoryId: '99',
          CategoryName: 'PRINCIPALES',
          IsRelevant: false,
        },
        CategoryInfos: [
          {
            CategoryId: '99',
            CategoryName: 'PRINCIPALES',
            IsRelevant: true,
          },
          {
            CategoryId: '90',
            CategoryName: 'SETS',
            IsRelevant: true,
          },
        ],
        GameType: 262,
        SmartMarketAvailable: false,
        Spov: '<Set>2',
        Name: 'Ganador del Set 2',
        NodeId: '7223674126',
        ParentNodeId: '7219795979',
        Priority: 9490,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 1.8,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224328390',
            GameTypeId: 262,
            GameSpecialOddsValue: '<Set>3',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham',
            NodeId: '7224328398',
            ParentNodeId: '7224328390',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 1.9,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224328390',
            GameTypeId: 262,
            GameSpecialOddsValue: '<Set>3',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda',
            NodeId: '7224328397',
            ParentNodeId: '7224328390',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonline',
        CategoryInfo: {
          CategoryId: '99',
          CategoryName: 'PRINCIPALES',
          IsRelevant: false,
        },
        CategoryInfos: [
          {
            CategoryId: '99',
            CategoryName: 'PRINCIPALES',
            IsRelevant: true,
          },
          {
            CategoryId: '90',
            CategoryName: 'SETS',
            IsRelevant: true,
          },
        ],
        GameType: 262,
        SmartMarketAvailable: false,
        Spov: '<Set>3',
        Name: 'Ganador del Set 3',
        NodeId: '7224328390',
        ParentNodeId: '7219795979',
        Priority: 9490,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 2,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224326099',
            GameTypeId: 1702,
            GameSpecialOddsValue: '<Set>2|<Spov>9.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda & Más 9.5',
            NodeId: '7224326149',
            ParentNodeId: '7224326099',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 3.6,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224326099',
            GameTypeId: 1702,
            GameSpecialOddsValue: '<Set>2|<Spov>9.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda & Menos 9.5',
            NodeId: '7224326150',
            ParentNodeId: '7224326099',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 8.5,
            SortOrder: 3,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224326099',
            GameTypeId: 1702,
            GameSpecialOddsValue: '<Set>2|<Spov>9.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham & Menos 9.5',
            NodeId: '7224326152',
            ParentNodeId: '7224326099',
            Priority: 3,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 4.25,
            SortOrder: 2,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224326099',
            GameTypeId: 1702,
            GameSpecialOddsValue: '<Set>2|<Spov>9.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham & Más 9.5',
            NodeId: '7224326151',
            ParentNodeId: '7224326099',
            Priority: 2,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonlist',
        CategoryInfo: {
          CategoryId: '90',
          CategoryName: 'SETS',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '90',
            CategoryName: 'SETS',
            IsRelevant: true,
          },
        ],
        GameType: 1702,
        SmartMarketAvailable: false,
        Spov: '<Set>2|<Spov>9.5',
        Name: 'Ganador y Total de Juegos Más/Menos en el Set 2',
        NodeId: '7224326099',
        ParentNodeId: '7219795979',
        Priority: 0,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 4,
            SortOrder: 3,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224408171',
            GameTypeId: 1702,
            GameSpecialOddsValue: '<Set>2|<Spov>10.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham & Menos 10.5',
            NodeId: '7224408186',
            ParentNodeId: '7224408171',
            Priority: 3,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 5.5,
            SortOrder: 2,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224408171',
            GameTypeId: 1702,
            GameSpecialOddsValue: '<Set>2|<Spov>10.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham & Más 10.5',
            NodeId: '7224408185',
            ParentNodeId: '7224408171',
            Priority: 2,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 4.5,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224408171',
            GameTypeId: 1702,
            GameSpecialOddsValue: '<Set>2|<Spov>10.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda & Más 10.5',
            NodeId: '7224408183',
            ParentNodeId: '7224408171',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 2.1,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224408171',
            GameTypeId: 1702,
            GameSpecialOddsValue: '<Set>2|<Spov>10.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda & Menos 10.5',
            NodeId: '7224408184',
            ParentNodeId: '7224408171',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonlist',
        CategoryInfo: {
          CategoryId: '90',
          CategoryName: 'SETS',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '90',
            CategoryName: 'SETS',
            IsRelevant: true,
          },
        ],
        GameType: 1702,
        SmartMarketAvailable: false,
        Spov: '<Set>2|<Spov>10.5',
        Name: 'Ganador y Total de Juegos Más/Menos en el Set 2',
        NodeId: '7224408171',
        ParentNodeId: '7219795979',
        Priority: 0,
        SportHandle: 'tennis',
        Locked: true,
      },
      {
        Results: [
          {
            Odd: 2.7,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224326100',
            GameTypeId: 147,
            GameSpecialOddsValue: '<Set>2|<Spov>1.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham -1.5',
            NodeId: '7224326155',
            ParentNodeId: '7224326100',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 1.4,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224326100',
            GameTypeId: 147,
            GameSpecialOddsValue: '<Set>2|<Spov>1.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda +1.5',
            NodeId: '7224326154',
            ParentNodeId: '7224326100',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonline',
        CategoryInfo: {
          CategoryId: '90',
          CategoryName: 'SETS',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '90',
            CategoryName: 'SETS',
            IsRelevant: true,
          },
        ],
        GameType: 147,
        SmartMarketAvailable: false,
        Spov: '<Set>2|<Spov>1.5',
        Name: 'Handicap de Juegos en el Set 2',
        NodeId: '7224326100',
        ParentNodeId: '7219795979',
        Priority: 9300,
        SportHandle: 'tennis',
        Locked: true,
      },
      {
        Results: [
          {
            Odd: 2.3,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224326094',
            GameTypeId: 147,
            GameSpecialOddsValue: '<Set>2|<Spov>-1.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham +1.5',
            NodeId: '7224326128',
            ParentNodeId: '7224326094',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 1.55,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224326094',
            GameTypeId: 147,
            GameSpecialOddsValue: '<Set>2|<Spov>-1.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda -1.5',
            NodeId: '7224326127',
            ParentNodeId: '7224326094',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonline',
        CategoryInfo: {
          CategoryId: '90',
          CategoryName: 'SETS',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '90',
            CategoryName: 'SETS',
            IsRelevant: true,
          },
        ],
        GameType: 147,
        SmartMarketAvailable: false,
        Spov: '<Set>2|<Spov>-1.5',
        Name: 'Handicap de Juegos en el Set 2',
        NodeId: '7224326094',
        ParentNodeId: '7219795979',
        Priority: 9300,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 2.55,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7223707627',
            GameTypeId: 201,
            GameSpecialOddsValue: '<Spov>-4.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham +4.5',
            NodeId: '7223707634',
            ParentNodeId: '7223707627',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 1.45,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7223707627',
            GameTypeId: 201,
            GameSpecialOddsValue: '<Spov>-4.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda -4.5',
            NodeId: '7223707633',
            ParentNodeId: '7223707627',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonline',
        CategoryInfo: {
          CategoryId: '99',
          CategoryName: 'PRINCIPALES',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '99',
            CategoryName: 'PRINCIPALES',
            IsRelevant: true,
          },
        ],
        GameType: 201,
        SmartMarketAvailable: false,
        Spov: '<Spov>-4.5',
        Name: 'Hándicap por Juegos',
        NodeId: '7223707627',
        ParentNodeId: '7219795979',
        Priority: 9475,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 7.5,
            SortOrder: 3,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224408169',
            GameTypeId: 1637,
            GameSpecialOddsValue: '<Set>2|<Game>5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda a 40',
            NodeId: '7224408176',
            ParentNodeId: '7224408169',
            Priority: 3,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 3.75,
            SortOrder: 7,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224408169',
            GameTypeId: 1637,
            GameSpecialOddsValue: '<Set>2|<Game>5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham a 40',
            NodeId: '7224408180',
            ParentNodeId: '7224408169',
            Priority: 7,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 6.5,
            SortOrder: 6,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224408169',
            GameTypeId: 1637,
            GameSpecialOddsValue: '<Set>2|<Game>5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham a 30',
            NodeId: '7224408179',
            ParentNodeId: '7224408169',
            Priority: 6,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 5,
            SortOrder: 2,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224408169',
            GameTypeId: 1637,
            GameSpecialOddsValue: '<Set>2|<Game>5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda a 30',
            NodeId: '7224408175',
            ParentNodeId: '7224408169',
            Priority: 2,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 5,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224408169',
            GameTypeId: 1637,
            GameSpecialOddsValue: '<Set>2|<Game>5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda a 0',
            NodeId: '7224408173',
            ParentNodeId: '7224408169',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 4.25,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224408169',
            GameTypeId: 1637,
            GameSpecialOddsValue: '<Set>2|<Game>5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda a 15',
            NodeId: '7224408174',
            ParentNodeId: '7224408169',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonlist',
        CategoryInfo: {
          CategoryId: '95',
          CategoryName: 'JUEGOS',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '95',
            CategoryName: 'JUEGOS',
            IsRelevant: true,
          },
        ],
        GameType: 1637,
        SmartMarketAvailable: false,
        Spov: '<Set>2|<Game>5',
        Name: 'Resultado Correcto del Juego 5 del Set 2',
        NodeId: '7224408169',
        ParentNodeId: '7219795979',
        Priority: 9300,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 5.5,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224418502',
            GameTypeId: 1637,
            GameSpecialOddsValue: '<Set>2|<Game>6',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda a 0',
            NodeId: '7224418506',
            ParentNodeId: '7224418502',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 3.8,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224418502',
            GameTypeId: 1637,
            GameSpecialOddsValue: '<Set>2|<Game>6',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda a 15',
            NodeId: '7224418507',
            ParentNodeId: '7224418502',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 4,
            SortOrder: 2,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224418502',
            GameTypeId: 1637,
            GameSpecialOddsValue: '<Set>2|<Game>6',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda a 30',
            NodeId: '7224418508',
            ParentNodeId: '7224418502',
            Priority: 2,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 4.5,
            SortOrder: 3,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224418502',
            GameTypeId: 1637,
            GameSpecialOddsValue: '<Set>2|<Game>6',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda a 40',
            NodeId: '7224418509',
            ParentNodeId: '7224418502',
            Priority: 3,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 30,
            SortOrder: 4,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224418502',
            GameTypeId: 1637,
            GameSpecialOddsValue: '<Set>2|<Game>6',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham a 0',
            NodeId: '7224418510',
            ParentNodeId: '7224418502',
            Priority: 4,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 15,
            SortOrder: 5,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224418502',
            GameTypeId: 1637,
            GameSpecialOddsValue: '<Set>2|<Game>6',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham a 15',
            NodeId: '7224418511',
            ParentNodeId: '7224418502',
            Priority: 5,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 10,
            SortOrder: 6,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224418502',
            GameTypeId: 1637,
            GameSpecialOddsValue: '<Set>2|<Game>6',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham a 30',
            NodeId: '7224418512',
            ParentNodeId: '7224418502',
            Priority: 6,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 11,
            SortOrder: 7,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224418502',
            GameTypeId: 1637,
            GameSpecialOddsValue: '<Set>2|<Game>6',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham a 40',
            NodeId: '7224418513',
            ParentNodeId: '7224418502',
            Priority: 7,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonlist',
        CategoryInfo: {
          CategoryId: '95',
          CategoryName: 'JUEGOS',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '95',
            CategoryName: 'JUEGOS',
            IsRelevant: true,
          },
        ],
        GameType: 1637,
        SmartMarketAvailable: false,
        Spov: '<Set>2|<Game>6',
        Name: 'Resultado Correcto del Juego 6 del Set 2',
        NodeId: '7224418502',
        ParentNodeId: '7219795979',
        Priority: 9300,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 1.3,
            SortOrder: 6,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7220055435',
            GameTypeId: 261,
            GameSpecialOddsValue: '',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda 2:0',
            NodeId: '7220055436',
            ParentNodeId: '7220055435',
            Priority: 6,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 5,
            SortOrder: 8,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7220055435',
            GameTypeId: 261,
            GameSpecialOddsValue: '',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda 2:1',
            NodeId: '7220055437',
            ParentNodeId: '7220055435',
            Priority: 8,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 5,
            SortOrder: 9,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7220055435',
            GameTypeId: 261,
            GameSpecialOddsValue: '',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham 2:1',
            NodeId: '7220055439',
            ParentNodeId: '7220055435',
            Priority: 9,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonlist',
        CategoryInfo: {
          CategoryId: '99',
          CategoryName: 'PRINCIPALES',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '99',
            CategoryName: 'PRINCIPALES',
            IsRelevant: true,
          },
        ],
        GameType: 261,
        SmartMarketAvailable: false,
        Spov: '',
        Name: 'Resultado final (por sets)',
        NodeId: '7220055435',
        ParentNodeId: '7219795979',
        Priority: 9375,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 6.5,
            SortOrder: 4,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7221794550',
            GameTypeId: 366,
            GameSpecialOddsValue: '<Set>2',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda 6:2',
            NodeId: '7221794555',
            ParentNodeId: '7221794550',
            Priority: 4,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 7,
            SortOrder: 6,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7221794550',
            GameTypeId: 366,
            GameSpecialOddsValue: '<Set>2',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda 6:3',
            NodeId: '7221794556',
            ParentNodeId: '7221794550',
            Priority: 6,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 3,
            SortOrder: 8,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7221794550',
            GameTypeId: 366,
            GameSpecialOddsValue: '<Set>2',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda 6:4',
            NodeId: '7221794557',
            ParentNodeId: '7221794550',
            Priority: 8,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 12,
            SortOrder: 10,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7221794550',
            GameTypeId: 366,
            GameSpecialOddsValue: '<Set>2',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda 7:5',
            NodeId: '7221794558',
            ParentNodeId: '7221794550',
            Priority: 10,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 8,
            SortOrder: 12,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7221794550',
            GameTypeId: 366,
            GameSpecialOddsValue: '<Set>2',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Renta Tokuda 7:6',
            NodeId: '7221794559',
            ParentNodeId: '7221794550',
            Priority: 12,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 35,
            SortOrder: 5,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7221794550',
            GameTypeId: 366,
            GameSpecialOddsValue: '<Set>2',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham 6:2',
            NodeId: '7221794562',
            ParentNodeId: '7221794550',
            Priority: 5,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 9,
            SortOrder: 7,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7221794550',
            GameTypeId: 366,
            GameSpecialOddsValue: '<Set>2',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham 6:3',
            NodeId: '7221794563',
            ParentNodeId: '7221794550',
            Priority: 7,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 12,
            SortOrder: 9,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7221794550',
            GameTypeId: 366,
            GameSpecialOddsValue: '<Set>2',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham 6:4',
            NodeId: '7221794564',
            ParentNodeId: '7221794550',
            Priority: 9,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 15,
            SortOrder: 11,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7221794550',
            GameTypeId: 366,
            GameSpecialOddsValue: '<Set>2',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham 7:5',
            NodeId: '7221794565',
            ParentNodeId: '7221794550',
            Priority: 11,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 9,
            SortOrder: 13,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7221794550',
            GameTypeId: 366,
            GameSpecialOddsValue: '<Set>2',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Rubin Statham 7:6',
            NodeId: '7221794566',
            ParentNodeId: '7221794550',
            Priority: 13,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonlist',
        CategoryInfo: {
          CategoryId: '90',
          CategoryName: 'SETS',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '90',
            CategoryName: 'SETS',
            IsRelevant: true,
          },
        ],
        GameType: 366,
        SmartMarketAvailable: false,
        Spov: '<Set>2',
        Name: 'Resultado Final del Set 2',
        NodeId: '7221794550',
        ParentNodeId: '7219795979',
        Priority: 9350,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 2.55,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224326101',
            GameTypeId: 1090,
            GameSpecialOddsValue: '<Set>2|<Spov>9.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Menos de 9.5',
            NodeId: '7224326157',
            ParentNodeId: '7224326101',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 1.45,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224326101',
            GameTypeId: 1090,
            GameSpecialOddsValue: '<Set>2|<Spov>9.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Más de 9.5',
            NodeId: '7224326156',
            ParentNodeId: '7224326101',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonline',
        CategoryInfo: {
          CategoryId: '90',
          CategoryName: 'SETS',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '90',
            CategoryName: 'SETS',
            IsRelevant: true,
          },
        ],
        GameType: 1090,
        SmartMarketAvailable: false,
        Spov: '<Set>2|<Spov>9.5',
        Name: 'Set 2 - Más/Menos Juegos Totales',
        NodeId: '7224326101',
        ParentNodeId: '7219795979',
        Priority: 9325,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 2.95,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224333659',
            GameTypeId: 1090,
            GameSpecialOddsValue: '<Set>2|<Spov>10.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Más de 10.5',
            NodeId: '7224333661',
            ParentNodeId: '7224333659',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 1.35,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224333659',
            GameTypeId: 1090,
            GameSpecialOddsValue: '<Set>2|<Spov>10.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Menos de 10.5',
            NodeId: '7224333662',
            ParentNodeId: '7224333659',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonline',
        CategoryInfo: {
          CategoryId: '90',
          CategoryName: 'SETS',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '90',
            CategoryName: 'SETS',
            IsRelevant: true,
          },
        ],
        GameType: 1090,
        SmartMarketAvailable: false,
        Spov: '<Set>2|<Spov>10.5',
        Name: 'Set 2 - Más/Menos Juegos Totales',
        NodeId: '7224333659',
        ParentNodeId: '7219795979',
        Priority: 9325,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 2,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224330229',
            GameTypeId: 195,
            GameSpecialOddsValue: '<Spov>19.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Más 19.5',
            NodeId: '7224330237',
            ParentNodeId: '7224330229',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 1.72,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224330229',
            GameTypeId: 195,
            GameSpecialOddsValue: '<Spov>19.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Menos 19.5',
            NodeId: '7224330238',
            ParentNodeId: '7224330229',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonline',
        CategoryInfo: {
          CategoryId: '99',
          CategoryName: 'PRINCIPALES',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '99',
            CategoryName: 'PRINCIPALES',
            IsRelevant: true,
          },
        ],
        GameType: 195,
        SmartMarketAvailable: false,
        Spov: '<Spov>19.5',
        Name: 'Total de Juegos Más/Menos',
        NodeId: '7224330229',
        ParentNodeId: '7219795979',
        Priority: 9450,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 1.9,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7220302211',
            GameTypeId: 195,
            GameSpecialOddsValue: '<Spov>21.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Más 21.5',
            NodeId: '7220302212',
            ParentNodeId: '7220302211',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 1.8,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7220302211',
            GameTypeId: 195,
            GameSpecialOddsValue: '<Spov>21.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Menos 21.5',
            NodeId: '7220302213',
            ParentNodeId: '7220302211',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonline',
        CategoryInfo: {
          CategoryId: '99',
          CategoryName: 'PRINCIPALES',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '99',
            CategoryName: 'PRINCIPALES',
            IsRelevant: true,
          },
        ],
        GameType: 195,
        SmartMarketAvailable: false,
        Spov: '<Spov>21.5',
        Name: 'Total de Juegos Más/Menos',
        NodeId: '7220302211',
        ParentNodeId: '7219795979',
        Priority: 9450,
        SportHandle: 'tennis',
        Locked: true,
      },
      {
        Results: [
          {
            Odd: 1.65,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224409757',
            GameTypeId: 1703,
            GameSpecialOddsValue: '<Set>2|<Game>5|<Spov>5.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Más 5.5',
            NodeId: '7224409760',
            ParentNodeId: '7224409757',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 2.1,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224409757',
            GameTypeId: 1703,
            GameSpecialOddsValue: '<Set>2|<Game>5|<Spov>5.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Menos 5.5',
            NodeId: '7224409761',
            ParentNodeId: '7224409757',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonlist',
        CategoryInfo: {
          CategoryId: '95',
          CategoryName: 'JUEGOS',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '95',
            CategoryName: 'JUEGOS',
            IsRelevant: true,
          },
        ],
        GameType: 1703,
        SmartMarketAvailable: false,
        Spov: '<Set>2|<Game>5|<Spov>5.5',
        Name: 'Total de Puntos Más/Menos en el Juego 5 del Set 2',
        NodeId: '7224409757',
        ParentNodeId: '7219795979',
        Priority: 0,
        SportHandle: 'tennis',
        Locked: true,
      },
      {
        Results: [
          {
            Odd: 1.72,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224418967',
            GameTypeId: 1703,
            GameSpecialOddsValue: '<Set>2|<Game>6|<Spov>5.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Más 5.5',
            NodeId: '7224418968',
            ParentNodeId: '7224418967',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 2,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7224418967',
            GameTypeId: 1703,
            GameSpecialOddsValue: '<Set>2|<Game>6|<Spov>5.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Menos 5.5',
            NodeId: '7224418969',
            ParentNodeId: '7224418967',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonlist',
        CategoryInfo: {
          CategoryId: '95',
          CategoryName: 'JUEGOS',
          IsRelevant: true,
        },
        CategoryInfos: [
          {
            CategoryId: '95',
            CategoryName: 'JUEGOS',
            IsRelevant: true,
          },
        ],
        GameType: 1703,
        SmartMarketAvailable: false,
        Spov: '<Set>2|<Game>6|<Spov>5.5',
        Name: 'Total de Puntos Más/Menos en el Juego 6 del Set 2',
        NodeId: '7224418967',
        ParentNodeId: '7219795979',
        Priority: 0,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Results: [
          {
            Odd: 2.95,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7223667439',
            GameTypeId: 199,
            GameSpecialOddsValue: '<Spov>2.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Más 2.5',
            NodeId: '7223667480',
            ParentNodeId: '7223667439',
            Priority: 0,
            SportHandle: 'tennis',
            Locked: false,
          },
          {
            Odd: 1.35,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819846742',
            LocationId: '3040678249',
            LeagueId: '6079519156',
            EventId: '7219795979',
            EventHasHandicap: false,
            GameId: '7223667439',
            GameTypeId: 199,
            GameSpecialOddsValue: '<Spov>2.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Menos 2.5',
            NodeId: '7223667481',
            ParentNodeId: '7223667439',
            Priority: 1,
            SportHandle: 'tennis',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonlist',
        CategoryInfo: {
          CategoryId: '99',
          CategoryName: 'PRINCIPALES',
          IsRelevant: false,
        },
        CategoryInfos: [
          {
            CategoryId: '99',
            CategoryName: 'PRINCIPALES',
            IsRelevant: true,
          },
          {
            CategoryId: '90',
            CategoryName: 'SETS',
            IsRelevant: true,
          },
        ],
        GameType: 199,
        SmartMarketAvailable: false,
        Spov: '<Spov>2.5',
        Name: 'Total de sets',
        NodeId: '7223667439',
        ParentNodeId: '7219795979',
        Priority: 0,
        SportHandle: 'tennis',
        Locked: false,
      },
    ],
    StreamingId: '384883',
    StreamingEnabled: 'img',
    LTMEnabled: true,
    LeagueKlothoPriority: 200,
    HighlightPriority: 14,
    Name: 'Renta Tokuda - Rubin Statham',
    NodeId: '7219795979',
    ParentNodeId: '6079519156',
    Priority: 0,
    SportHandle: 'tennis',
    Locked: false,
  },
  '6760114061': {
    ResultInfo: "1-5 83'",
    DefaultGame: null,
    liveData: {
      YellowCardsHome: 1,
      RedCardsHome: 0,
      YellowCardsAway: 1,
      RedCardsAway: 0,
      ParticipantHome: 'Sagan Tosu',
      ParticipantAway: 'Shonan Bellmare',
      Period: 3,
      PeriodName: '2º Tiempo',
      Actions: [
        {
          Period: 3,
          PeriodName: '2º Tiempo',
          Time: 64,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 3,
          PeriodName: '2º Tiempo',
          Time: 64,
          ActionType: 1,
          ActionTypeName: 'Corner',
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 3,
          PeriodName: '2º Tiempo',
          Time: 63,
          ActionType: 2,
          ActionTypeName: 'Gol',
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 3,
          PeriodName: '2º Tiempo',
          Time: 63,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 3,
          PeriodName: '2º Tiempo',
          Time: 63,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 3,
          PeriodName: '2º Tiempo',
          Time: 62,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 3,
          PeriodName: '2º Tiempo',
          Time: 59,
          ActionType: 2,
          ActionTypeName: 'Gol',
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 3,
          PeriodName: '2º Tiempo',
          Time: 58,
          ActionType: 1,
          ActionTypeName: 'Corner',
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: true,
        },
        {
          Period: 3,
          PeriodName: '2º Tiempo',
          Time: 57,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: true,
        },
        {
          Period: 3,
          PeriodName: '2º Tiempo',
          Time: 57,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: true,
        },
        {
          Period: 3,
          PeriodName: '2º Tiempo',
          Time: 57,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: true,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 53,
          ActionType: 2,
          ActionTypeName: 'Gol',
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: true,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 49,
          ActionType: 2,
          ActionTypeName: 'Gol',
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 44,
          ActionType: 5,
          ActionTypeName: 'Tarjeta Amarilla',
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 44,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 44,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 39,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 36,
          ActionType: 2,
          ActionTypeName: 'Gol',
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 29,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: true,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 28,
          ActionType: 5,
          ActionTypeName: 'Tarjeta Amarilla',
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: true,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 28,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: true,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 22,
          ActionType: 1,
          ActionTypeName: 'Corner',
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 21,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 21,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 21,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 12,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: true,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 7,
          ActionType: 1,
          ActionTypeName: 'Corner',
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: true,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 6,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: true,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 6,
          ActionType: -1,
          ActionTypeName: null,
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: true,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 2,
          ActionType: 2,
          ActionTypeName: 'Gol',
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
        {
          Period: 2,
          PeriodName: '1º Tiempo',
          Time: 0,
          ActionType: 14,
          ActionTypeName: 'Patada inicial',
          Participant: '',
          AffectedParticipant: '',
          IsHomeTeam: false,
        },
      ],
      ResultHome: 1,
      ResultAway: 5,
      Time: '07:00',
      MatchTime: 83,
      RemainingPeriodTime: '',
    },
    StartDate: '/Date(1676700000000)/',
    StarDate: '/Date(1676700000000)/',
    isLive: true,
    LeagueName: 'J1 League',
    ChildrenCount: 15,
    SportName: 'Fútbol',
    CountryCode: 'JP',
    CountryName: 'Japón',
    Participants: [
      {
        ExtensionData: {},
        AdditionalValues: {
          KeyValues: [],
          LocalizedValues: [
            {
              Key: 'ParticipantOrder',
              Value: '1',
            },
          ],
          ExtensionData: {},
          ReferenceId: 0,
        },
        Id: 15237071,
        IsHome: false,
        LocalizedNames: {
          LocalizedValues: [
            {
              ExtensionData: {},
              CountryCode: '-1',
              LanguageCode: '-1',
              Value: 'Shonan Bellmare',
            },
          ],
          ExtensionData: {},
          ReferenceId: -1,
        },
        LocalizedShortNames: {
          LocalizedValues: [
            {
              ExtensionData: {},
              CountryCode: '-1',
              LanguageCode: '-1',
              Value: 'SBe',
            },
          ],
          ExtensionData: {},
          ReferenceId: 0,
        },
      },
      {
        ExtensionData: {},
        AdditionalValues: {
          KeyValues: [],
          LocalizedValues: [
            {
              Key: 'ParticipantOrder',
              Value: '0',
            },
          ],
          ExtensionData: {},
          ReferenceId: 0,
        },
        Id: 15237858,
        IsHome: true,
        LocalizedNames: {
          LocalizedValues: [
            {
              ExtensionData: {},
              CountryCode: '-1',
              LanguageCode: '-1',
              Value: 'Sagan Tosu',
            },
          ],
          ExtensionData: {},
          ReferenceId: -1,
        },
        LocalizedShortNames: {
          LocalizedValues: [
            {
              ExtensionData: {},
              CountryCode: '-1',
              LanguageCode: '-1',
              Value: 'STo',
            },
          ],
          ExtensionData: {},
          ReferenceId: 0,
        },
      },
    ],
    LiveHistory: null,
    SmartMarketReferenceGameTypeIds: '4;18;46;54;62;74;75;76;139;374||all',
    StatisticsId: '38389181',
    SportId: '2817453298',
    Games: [
      {
        Results: [
          {
            Odd: 2.4,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2817453298',
            LocationId: '3006581819',
            LeagueId: '3009137309',
            EventId: '6649152292',
            EventHasHandicap: false,
            GameId: '6760114061',
            GameTypeId: 18,
            GameSpecialOddsValue: '<Spov>6.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Más 6.5',
            NodeId: '6760114101',
            ParentNodeId: '6760114061',
            Priority: 0,
            SportHandle: 'soccer',
            Locked: false,
          },
          {
            Odd: 1.5,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2817453298',
            LocationId: '3006581819',
            LeagueId: '3009137309',
            EventId: '6649152292',
            EventHasHandicap: false,
            GameId: '6760114061',
            GameTypeId: 18,
            GameSpecialOddsValue: '<Spov>6.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Menos 6.5',
            NodeId: '6760114102',
            ParentNodeId: '6760114061',
            Priority: 1,
            SportHandle: 'soccer',
            Locked: false,
          },
        ],
        DisplayTypeName: '2buttonline',
        CategoryInfo: {
          CategoryId: '99',
          CategoryName: 'PRINCIPALES',
          IsRelevant: false,
        },
        CategoryInfos: [
          {
            CategoryId: '99',
            CategoryName: 'PRINCIPALES',
            IsRelevant: true,
          },
          {
            CategoryId: '82',
            CategoryName: 'GOLES',
            IsRelevant: false,
          },
        ],
        GameType: 18,
        SmartMarketAvailable: true,
        Spov: '<Spov>6.5',
        Name: 'Más/Menos Total Goles',
        NodeId: '6760114061',
        ParentNodeId: '6649152292',
        Priority: 9965,
        SportHandle: 'soccer',
        Locked: false,
      },
    ],
    StreamingId: null,
    StreamingEnabled: null,
    LTMEnabled: true,
    LeagueKlothoPriority: 4200,
    HighlightPriority: 9,
    Name: 'Sagan Tosu - Shonan Bellmare',
    NodeId: '6649152292',
    ParentNodeId: '3009137309',
    Priority: 0,
    SportHandle: 'soccer',
    Locked: false,
  },
};
export const userDataSlice = {
  firstName: 'Juan David',
  lastName: 'lastName',
  email: '',
  password: '',
  phone: '',
  id: '1053783846',
  bets: {
    '9f996fbf81e9': {
      couponData: {
        '6760210303': {
          game: {
            Results: [
              {
                Odd: 1.65,
                SortOrder: 0,
                IsLive: true,
                upOdd: false,
                downOdd: false,
                IsNonRunner: false,
                SportId: '2817453298',
                LocationId: '2817453310',
                LeagueId: '3009130476',
                EventId: '6744932314',
                EventHasHandicap: false,
                GameId: '6760210236',
                GameTypeId: 18,
                GameSpecialOddsValue: '<Spov>1.5',
                GameBetTypeAvailability: 0,
                GameNumberOfStarters: 0,
                Name: 'Más 1.5',
                NodeId: '6760210303',
                ParentNodeId: '6760210236',
                Priority: 0,
                SportHandle: 'soccer',
                Locked: false,
              },
              {
                Odd: 2.1,
                SortOrder: 1,
                IsLive: true,
                upOdd: false,
                downOdd: false,
                IsNonRunner: false,
                SportId: '2817453298',
                LocationId: '2817453310',
                LeagueId: '3009130476',
                EventId: '6744932314',
                EventHasHandicap: false,
                GameId: '6760210236',
                GameTypeId: 18,
                GameSpecialOddsValue: '<Spov>1.5',
                GameBetTypeAvailability: 0,
                GameNumberOfStarters: 0,
                Name: 'Menos 1.5',
                NodeId: '6760210304',
                ParentNodeId: '6760210236',
                Priority: 1,
                SportHandle: 'soccer',
                Locked: false,
              },
            ],
            DisplayTypeName: '2buttonline',
            CategoryInfo: {
              CategoryId: '99',
              CategoryName: 'PRINCIPALES',
              IsRelevant: false,
            },
            CategoryInfos: [
              {
                CategoryId: '99',
                CategoryName: 'PRINCIPALES',
                IsRelevant: true,
              },
              {
                CategoryId: '82',
                CategoryName: 'GOLES',
                IsRelevant: false,
              },
            ],
            GameType: 18,
            SmartMarketAvailable: true,
            Spov: '<Spov>1.5',
            Name: 'Más/Menos Total Goles',
            NodeId: '6760210236',
            ParentNodeId: '6744932314',
            Priority: 9965,
            SportHandle: 'soccer',
            Locked: false,
          },
          result: {
            Odd: 1.65,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2817453298',
            LocationId: '2817453310',
            LeagueId: '3009130476',
            EventId: '6744932314',
            EventHasHandicap: false,
            GameId: '6760210236',
            GameTypeId: 18,
            GameSpecialOddsValue: '<Spov>1.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Más 1.5',
            NodeId: '6760210303',
            ParentNodeId: '6760210236',
            Priority: 0,
            SportHandle: 'soccer',
            Locked: false,
          },
          name: 'Altona Magic SC - Hume City',
          locks: {
            eventOverview: false,
            oddsOverview: false,
          },
        },
      },
      time: '2023-06-12T18:01:27.821Z',
      couponFooter: {
        combined: true,
        betEarnings: 16.5,
        betOddWithMultipleBets: '1.65',
        totalBet: '10',
        betsDivided: {
          '6760210303': '',
        },
        error: false,
        state: 'Pendiente',
        notCombinedBetsState: {},
      },
    },
  },
};
export const userActionsSlice = {
  expandCoupon: false,
  makeBet: false,
  approveBet: null,
  connectionError: '',
  roomToDelete: '',
  displayLiveDetail: {
    '6744932314': {
      parentNodeId: '6744932314',
      name: 'Altona Magic SC - Hume City',
      locks: {
        eventOverview: false,
        oddsOverview: false,
      },
    },
  },
  lastLiveDetailId: '6744932314',
};

export const codereDataSlice = getHomeLiveEvents;
