import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import BetsTable from './BetsTable';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../../styles/theme';
import { BrowserRouter } from 'react-router-dom';
import { Provider } from 'react-redux';
import { setupStore } from '../../store/store';
export default {
  /* 👇 The title prop is optional.
   * See https://storybook.js.org/docs/react/configure/overview#configure-story-loading
   * to learn how to generate automatic titles
   */
  title: 'BetsTable',
  component: BetsTable,
} as ComponentMeta<typeof BetsTable>;

const userDataSlice = {
  firstName: 'Juan David',
  lastName: 'lastName',
  email: '',
  password: '',
  phone: '',
  id: '1053783846',
  bets: {
    fa2a4c5d0ea6: {
      couponData: {
        '6851831869': {
          game: {
            Results: [
              {
                Odd: 1.9,
                SortOrder: 0,
                IsLive: true,
                upOdd: false,
                downOdd: false,
                IsNonRunner: false,
                SportId: '2819853525',
                LocationId: '2819853531',
                LeagueId: '4762099350',
                EventId: '6849437045',
                EventHasHandicap: false,
                GameId: '6851831848',
                GameTypeId: 1828,
                GameSpecialOddsValue: '<Set>4',
                GameBetTypeAvailability: 0,
                GameNumberOfStarters: 0,
                Name: 'UC Irvine Anteaters',
                NodeId: '6851831868',
                ParentNodeId: '6851831848',
                Priority: 0,
                SportHandle: 'volleyball',
                Locked: false,
              },
              {
                Odd: 1.8,
                SortOrder: 1,
                IsLive: true,
                upOdd: false,
                downOdd: false,
                IsNonRunner: false,
                SportId: '2819853525',
                LocationId: '2819853531',
                LeagueId: '4762099350',
                EventId: '6849437045',
                EventHasHandicap: false,
                GameId: '6851831848',
                GameTypeId: 1828,
                GameSpecialOddsValue: '<Set>4',
                GameBetTypeAvailability: 0,
                GameNumberOfStarters: 0,
                Name: 'Penn State Nittany Lions',
                NodeId: '6851831869',
                ParentNodeId: '6851831848',
                Priority: 1,
                SportHandle: 'volleyball',
                Locked: false,
              },
            ],
            DisplayTypeName: '2buttonline',
            CategoryInfo: {
              CategoryId: '91',
              CategoryName: 'SETS',
              IsRelevant: true,
            },
            CategoryInfos: [
              {
                CategoryId: '91',
                CategoryName: 'SETS',
                IsRelevant: true,
              },
            ],
            GameType: 1828,
            SmartMarketAvailable: false,
            Spov: '<Set>4',
            Name: 'Ganador Set 4',
            NodeId: '6851831848',
            ParentNodeId: '6849437045',
            Priority: 9945,
            SportHandle: 'volleyball',
            Locked: false,
          },
          result: {
            Odd: 1.8,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819853525',
            LocationId: '2819853531',
            LeagueId: '4762099350',
            EventId: '6849437045',
            EventHasHandicap: false,
            GameId: '6851831848',
            GameTypeId: 1828,
            GameSpecialOddsValue: '<Set>4',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Penn State Nittany Lions',
            NodeId: '6851831869',
            ParentNodeId: '6851831848',
            Priority: 1,
            SportHandle: 'volleyball',
            Locked: false,
          },
          name: 'UC Irvine Anteaters - Penn State Nittany Lions',
          locks: {
            eventOverview: false,
            oddsOverview: false,
          },
        },
        '6851831868': {
          game: {
            Results: [
              {
                Odd: 1.9,
                SortOrder: 0,
                IsLive: true,
                upOdd: false,
                downOdd: false,
                IsNonRunner: false,
                SportId: '2819853525',
                LocationId: '2819853531',
                LeagueId: '4762099350',
                EventId: '6849437045',
                EventHasHandicap: false,
                GameId: '6851831848',
                GameTypeId: 1828,
                GameSpecialOddsValue: '<Set>4',
                GameBetTypeAvailability: 0,
                GameNumberOfStarters: 0,
                Name: 'UC Irvine Anteaters',
                NodeId: '6851831868',
                ParentNodeId: '6851831848',
                Priority: 0,
                SportHandle: 'volleyball',
                Locked: false,
              },
              {
                Odd: 1.8,
                SortOrder: 1,
                IsLive: true,
                upOdd: false,
                downOdd: false,
                IsNonRunner: false,
                SportId: '2819853525',
                LocationId: '2819853531',
                LeagueId: '4762099350',
                EventId: '6849437045',
                EventHasHandicap: false,
                GameId: '6851831848',
                GameTypeId: 1828,
                GameSpecialOddsValue: '<Set>4',
                GameBetTypeAvailability: 0,
                GameNumberOfStarters: 0,
                Name: 'Penn State Nittany Lions',
                NodeId: '6851831869',
                ParentNodeId: '6851831848',
                Priority: 1,
                SportHandle: 'volleyball',
                Locked: false,
              },
            ],
            DisplayTypeName: '2buttonline',
            CategoryInfo: {
              CategoryId: '91',
              CategoryName: 'SETS',
              IsRelevant: true,
            },
            CategoryInfos: [
              {
                CategoryId: '91',
                CategoryName: 'SETS',
                IsRelevant: true,
              },
            ],
            GameType: 1828,
            SmartMarketAvailable: false,
            Spov: '<Set>4',
            Name: 'Ganador Set 4',
            NodeId: '6851831848',
            ParentNodeId: '6849437045',
            Priority: 9945,
            SportHandle: 'volleyball',
            Locked: false,
          },
          result: {
            Odd: 1.9,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819853525',
            LocationId: '2819853531',
            LeagueId: '4762099350',
            EventId: '6849437045',
            EventHasHandicap: false,
            GameId: '6851831848',
            GameTypeId: 1828,
            GameSpecialOddsValue: '<Set>4',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'UC Irvine Anteaters',
            NodeId: '6851831868',
            ParentNodeId: '6851831848',
            Priority: 0,
            SportHandle: 'volleyball',
            Locked: false,
          },
          name: 'UC Irvine Anteaters - Penn State Nittany Lions',
          locks: {
            eventOverview: false,
            oddsOverview: false,
          },
        },
        '6851835116': {
          game: {
            Results: [
              {
                Odd: 1.85,
                SortOrder: 0,
                IsLive: true,
                upOdd: false,
                downOdd: false,
                IsNonRunner: false,
                SportId: '2819853525',
                LocationId: '2819853531',
                LeagueId: '4762099350',
                EventId: '6849437045',
                EventHasHandicap: false,
                GameId: '6851835113',
                GameTypeId: 393,
                GameSpecialOddsValue: '<Spov>212.5',
                GameBetTypeAvailability: 0,
                GameNumberOfStarters: 0,
                Name: 'Más 212.5',
                NodeId: '6851835115',
                ParentNodeId: '6851835113',
                Priority: 0,
                SportHandle: 'volleyball',
                Locked: false,
              },
              {
                Odd: 1.85,
                SortOrder: 1,
                IsLive: true,
                upOdd: false,
                downOdd: false,
                IsNonRunner: false,
                SportId: '2819853525',
                LocationId: '2819853531',
                LeagueId: '4762099350',
                EventId: '6849437045',
                EventHasHandicap: false,
                GameId: '6851835113',
                GameTypeId: 393,
                GameSpecialOddsValue: '<Spov>212.5',
                GameBetTypeAvailability: 0,
                GameNumberOfStarters: 0,
                Name: 'Menos 212.5',
                NodeId: '6851835116',
                ParentNodeId: '6851835113',
                Priority: 1,
                SportHandle: 'volleyball',
                Locked: false,
              },
            ],
            DisplayTypeName: '2buttonline',
            CategoryInfo: {
              CategoryId: '99',
              CategoryName: 'PRINCIPALES',
              IsRelevant: true,
            },
            CategoryInfos: [
              {
                CategoryId: '99',
                CategoryName: 'PRINCIPALES',
                IsRelevant: true,
              },
            ],
            GameType: 393,
            SmartMarketAvailable: false,
            Spov: '<Spov>212.5',
            Name: 'Más/Menos Puntos Totales',
            NodeId: '6851835113',
            ParentNodeId: '6849437045',
            Priority: 9985,
            SportHandle: 'volleyball',
            Locked: false,
          },
          result: {
            Odd: 1.85,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819853525',
            LocationId: '2819853531',
            LeagueId: '4762099350',
            EventId: '6849437045',
            EventHasHandicap: false,
            GameId: '6851835113',
            GameTypeId: 393,
            GameSpecialOddsValue: '<Spov>212.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Menos 212.5',
            NodeId: '6851835116',
            ParentNodeId: '6851835113',
            Priority: 1,
            SportHandle: 'volleyball',
            Locked: false,
          },
          name: 'UC Irvine Anteaters - Penn State Nittany Lions',
          locks: {
            eventOverview: false,
            oddsOverview: false,
          },
        },
      },
      time: '2023-05-04T09:18:11.501Z',
      couponFooter: {
        combined: true,
        betEarnings: 63.27,
        betOddWithMultipleBets: '6.33',
        totalBet: '10',
        betsDivided: {
          '6851831869': '',
          '6851831868': '',
          '6851835116': '',
        },
        error: false,
        state: 'Pendiente',
        notCombinedBetsState: {
          '6851831869': 'Pendienteee',
          '6851831868': 'Pendienteee',
          '6851835116': 'Pendienteee',
        },
      },
    },
    b36c7677f2c4: {
      couponData: {
        '6851831869': {
          game: {
            Results: [
              {
                Odd: 1.9,
                SortOrder: 0,
                IsLive: true,
                upOdd: false,
                downOdd: false,
                IsNonRunner: false,
                SportId: '2819853525',
                LocationId: '2819853531',
                LeagueId: '4762099350',
                EventId: '6849437045',
                EventHasHandicap: false,
                GameId: '6851831848',
                GameTypeId: 1828,
                GameSpecialOddsValue: '<Set>4',
                GameBetTypeAvailability: 0,
                GameNumberOfStarters: 0,
                Name: 'UC Irvine Anteaters',
                NodeId: '6851831868',
                ParentNodeId: '6851831848',
                Priority: 0,
                SportHandle: 'volleyball',
                Locked: false,
              },
              {
                Odd: 1.8,
                SortOrder: 1,
                IsLive: true,
                upOdd: false,
                downOdd: false,
                IsNonRunner: false,
                SportId: '2819853525',
                LocationId: '2819853531',
                LeagueId: '4762099350',
                EventId: '6849437045',
                EventHasHandicap: false,
                GameId: '6851831848',
                GameTypeId: 1828,
                GameSpecialOddsValue: '<Set>4',
                GameBetTypeAvailability: 0,
                GameNumberOfStarters: 0,
                Name: 'Penn State Nittany Lions',
                NodeId: '6851831869',
                ParentNodeId: '6851831848',
                Priority: 1,
                SportHandle: 'volleyball',
                Locked: false,
              },
            ],
            DisplayTypeName: '2buttonline',
            CategoryInfo: {
              CategoryId: '91',
              CategoryName: 'SETS',
              IsRelevant: true,
            },
            CategoryInfos: [
              {
                CategoryId: '91',
                CategoryName: 'SETS',
                IsRelevant: true,
              },
            ],
            GameType: 1828,
            SmartMarketAvailable: false,
            Spov: '<Set>4',
            Name: 'Ganador Set 4',
            NodeId: '6851831848',
            ParentNodeId: '6849437045',
            Priority: 9945,
            SportHandle: 'volleyball',
            Locked: false,
          },
          result: {
            Odd: 1.8,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819853525',
            LocationId: '2819853531',
            LeagueId: '4762099350',
            EventId: '6849437045',
            EventHasHandicap: false,
            GameId: '6851831848',
            GameTypeId: 1828,
            GameSpecialOddsValue: '<Set>4',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Penn State Nittany Lions',
            NodeId: '6851831869',
            ParentNodeId: '6851831848',
            Priority: 1,
            SportHandle: 'volleyball',
            Locked: false,
          },
          name: 'UC Irvine Anteaters - Penn State Nittany Lions',
          locks: {
            eventOverview: false,
            oddsOverview: false,
          },
        },
        '6851831868': {
          game: {
            Results: [
              {
                Odd: 1.9,
                SortOrder: 0,
                IsLive: true,
                upOdd: false,
                downOdd: false,
                IsNonRunner: false,
                SportId: '2819853525',
                LocationId: '2819853531',
                LeagueId: '4762099350',
                EventId: '6849437045',
                EventHasHandicap: false,
                GameId: '6851831848',
                GameTypeId: 1828,
                GameSpecialOddsValue: '<Set>4',
                GameBetTypeAvailability: 0,
                GameNumberOfStarters: 0,
                Name: 'UC Irvine Anteaters',
                NodeId: '6851831868',
                ParentNodeId: '6851831848',
                Priority: 0,
                SportHandle: 'volleyball',
                Locked: false,
              },
              {
                Odd: 1.8,
                SortOrder: 1,
                IsLive: true,
                upOdd: false,
                downOdd: false,
                IsNonRunner: false,
                SportId: '2819853525',
                LocationId: '2819853531',
                LeagueId: '4762099350',
                EventId: '6849437045',
                EventHasHandicap: false,
                GameId: '6851831848',
                GameTypeId: 1828,
                GameSpecialOddsValue: '<Set>4',
                GameBetTypeAvailability: 0,
                GameNumberOfStarters: 0,
                Name: 'Penn State Nittany Lions',
                NodeId: '6851831869',
                ParentNodeId: '6851831848',
                Priority: 1,
                SportHandle: 'volleyball',
                Locked: false,
              },
            ],
            DisplayTypeName: '2buttonline',
            CategoryInfo: {
              CategoryId: '91',
              CategoryName: 'SETS',
              IsRelevant: true,
            },
            CategoryInfos: [
              {
                CategoryId: '91',
                CategoryName: 'SETS',
                IsRelevant: true,
              },
            ],
            GameType: 1828,
            SmartMarketAvailable: false,
            Spov: '<Set>4',
            Name: 'Ganador Set 4',
            NodeId: '6851831848',
            ParentNodeId: '6849437045',
            Priority: 9945,
            SportHandle: 'volleyball',
            Locked: false,
          },
          result: {
            Odd: 1.9,
            SortOrder: 0,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819853525',
            LocationId: '2819853531',
            LeagueId: '4762099350',
            EventId: '6849437045',
            EventHasHandicap: false,
            GameId: '6851831848',
            GameTypeId: 1828,
            GameSpecialOddsValue: '<Set>4',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'UC Irvine Anteaters',
            NodeId: '6851831868',
            ParentNodeId: '6851831848',
            Priority: 0,
            SportHandle: 'volleyball',
            Locked: false,
          },
          name: 'UC Irvine Anteaters - Penn State Nittany Lions',
          locks: {
            eventOverview: false,
            oddsOverview: false,
          },
        },
        '6851835116': {
          game: {
            Results: [
              {
                Odd: 1.85,
                SortOrder: 0,
                IsLive: true,
                upOdd: false,
                downOdd: false,
                IsNonRunner: false,
                SportId: '2819853525',
                LocationId: '2819853531',
                LeagueId: '4762099350',
                EventId: '6849437045',
                EventHasHandicap: false,
                GameId: '6851835113',
                GameTypeId: 393,
                GameSpecialOddsValue: '<Spov>212.5',
                GameBetTypeAvailability: 0,
                GameNumberOfStarters: 0,
                Name: 'Más 212.5',
                NodeId: '6851835115',
                ParentNodeId: '6851835113',
                Priority: 0,
                SportHandle: 'volleyball',
                Locked: false,
              },
              {
                Odd: 1.85,
                SortOrder: 1,
                IsLive: true,
                upOdd: false,
                downOdd: false,
                IsNonRunner: false,
                SportId: '2819853525',
                LocationId: '2819853531',
                LeagueId: '4762099350',
                EventId: '6849437045',
                EventHasHandicap: false,
                GameId: '6851835113',
                GameTypeId: 393,
                GameSpecialOddsValue: '<Spov>212.5',
                GameBetTypeAvailability: 0,
                GameNumberOfStarters: 0,
                Name: 'Menos 212.5',
                NodeId: '6851835116',
                ParentNodeId: '6851835113',
                Priority: 1,
                SportHandle: 'volleyball',
                Locked: false,
              },
            ],
            DisplayTypeName: '2buttonline',
            CategoryInfo: {
              CategoryId: '99',
              CategoryName: 'PRINCIPALES',
              IsRelevant: true,
            },
            CategoryInfos: [
              {
                CategoryId: '99',
                CategoryName: 'PRINCIPALES',
                IsRelevant: true,
              },
            ],
            GameType: 393,
            SmartMarketAvailable: false,
            Spov: '<Spov>212.5',
            Name: 'Más/Menos Puntos Totales',
            NodeId: '6851835113',
            ParentNodeId: '6849437045',
            Priority: 9985,
            SportHandle: 'volleyball',
            Locked: false,
          },
          result: {
            Odd: 1.85,
            SortOrder: 1,
            IsLive: true,
            upOdd: false,
            downOdd: false,
            IsNonRunner: false,
            SportId: '2819853525',
            LocationId: '2819853531',
            LeagueId: '4762099350',
            EventId: '6849437045',
            EventHasHandicap: false,
            GameId: '6851835113',
            GameTypeId: 393,
            GameSpecialOddsValue: '<Spov>212.5',
            GameBetTypeAvailability: 0,
            GameNumberOfStarters: 0,
            Name: 'Menos 212.5',
            NodeId: '6851835116',
            ParentNodeId: '6851835113',
            Priority: 1,
            SportHandle: 'volleyball',
            Locked: false,
          },
          name: 'UC Irvine Anteaters - Penn State Nittany Lions',
          locks: {
            eventOverview: false,
            oddsOverview: false,
          },
        },
      },
      time: '2023-05-04T09:24:34.173Z',
      couponFooter: {
        combined: false,
        betEarnings: null,
        betOddWithMultipleBets: null,
        totalBet: '6',
        betsDivided: {
          '6851831869': '1',
          '6851831868': '2',
          '6851835116': '3',
        },
        error: false,
        state: 'Pendiente',
        notCombinedBetsState: {
          '6851831869': 'Pendienteee',
          '6851831868': 'Pendienteee',
          '6851835116': 'Pendienteee',
        },
      },
    },
  },
};

//👇 We create a “template” of how args map to rendering
const Template: ComponentStory<typeof BetsTable> = (args) => (
  <ThemeProvider theme={theme}>
    <Provider store={setupStore({ userData: userDataSlice })}>
      <BrowserRouter>
        <BetsTable {...args} />
      </BrowserRouter>
    </Provider>
  </ThemeProvider>
);

export const Component = Template.bind({});
Component.args = { betId: Object.keys(userDataSlice.bets)[0] };
