import React from 'react';
import { render } from '@testing-library/react';
import TabPanel from './TabPanel';
import { ThemeProvider } from '@emotion/react';
import { Provider } from 'react-redux';
import theme from '../../styles/theme';
import { setupStore } from '../../store/store';

describe('Render the markets available for a specific event', () => {
  it('Should render the title and odds of the specific event', () => {
    const { getByText, getAllByText } = render(
      <React.StrictMode>
        <ThemeProvider theme={theme}>
          <Provider store={setupStore()}>
            <TabPanel userActions={userActions} category={category} locked={false} />
          </Provider>
        </ThemeProvider>
      </React.StrictMode>
    );
    expect(getAllByText('1ª Parte - Más/Menos Total Goles')[0]).toBeInTheDocument();
    expect(getByText('Más 2.5')).toBeInTheDocument();
    expect(getByText('4.3')).toBeInTheDocument();
    expect(getByText('1.18')).toBeInTheDocument();
  });
  it('Should render the lock icon when true', () => {
    const { getByTestId } = render(
      <React.StrictMode>
        <ThemeProvider theme={theme}>
          <Provider store={setupStore()}>
            <TabPanel userActions={userActions} category={category} locked={true} />
            );
          </Provider>
        </ThemeProvider>
      </React.StrictMode>
    );
    expect(getByTestId('lock-icon')).toBeInTheDocument();
  });
});

export const userActions = {
  expandCoupon: false,
  makeBet: false,
  approveBet: null,
  connectionError: '',
  roomToDelete: '',
  displayLiveDetail: {
    '7248672410': {
      parentNodeId: '7248672410',
      name: 'Sydney Olympic Femenino - Macarthur Rams Femenino',
      locks: {
        eventOverview: false,
        oddsOverview: false,
      },
    },
  },
  lastLiveDetailId: '7248672410',
};
export const category = [
  {
    Results: [
      {
        Odd: 4.3,
        SortOrder: 0,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '103843409',
        LocationId: '103844889',
        LeagueId: '1044751943',
        EventId: '7248672410',
        EventHasHandicap: false,
        GameId: '7257831625',
        GameTypeId: 22,
        GameSpecialOddsValue: '<Spov>2.5',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: 'Más 2.5',
        NodeId: '7257831627',
        ParentNodeId: '7257831625',
        Priority: 0,
        SportHandle: 'soccer',
        Locked: false,
      },
      {
        Odd: 1.18,
        SortOrder: 1,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '103843409',
        LocationId: '103844889',
        LeagueId: '1044751943',
        EventId: '7248672410',
        EventHasHandicap: false,
        GameId: '7257831625',
        GameTypeId: 22,
        GameSpecialOddsValue: '<Spov>2.5',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: 'Menos 2.5',
        NodeId: '7257831628',
        ParentNodeId: '7257831625',
        Priority: 1,
        SportHandle: 'soccer',
        Locked: false,
      },
    ],
    DisplayTypeName: '2buttonline',
    CategoryInfo: {
      CategoryId: '60',
      CategoryName: 'GOLES',
      IsRelevant: false,
    },
    CategoryInfos: [
      {
        CategoryId: '60',
        CategoryName: 'GOLES',
        IsRelevant: false,
      },
      {
        CategoryId: '45',
        CategoryName: '1ª PARTE',
        IsRelevant: false,
      },
    ],
    GameType: 22,
    SmartMarketAvailable: false,
    Spov: '<Spov>2.5',
    Name: '1ª Parte - Más/Menos Total Goles',
    NodeId: '7257831625',
    ParentNodeId: '7248672410',
    Priority: 9822,
    SportHandle: 'soccer',
    Locked: false,
  },
  {
    Results: [
      {
        Odd: 2.1,
        SortOrder: 1,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '103843409',
        LocationId: '103844889',
        LeagueId: '1044751943',
        EventId: '7248672410',
        EventHasHandicap: false,
        GameId: '7248672430',
        GameTypeId: 22,
        GameSpecialOddsValue: '<Spov>1.5',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: 'Menos 1.5',
        NodeId: '7248672527',
        ParentNodeId: '7248672430',
        Priority: 1,
        SportHandle: 'soccer',
        Locked: false,
      },
      {
        Odd: 1.65,
        SortOrder: 0,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '103843409',
        LocationId: '103844889',
        LeagueId: '1044751943',
        EventId: '7248672410',
        EventHasHandicap: false,
        GameId: '7248672430',
        GameTypeId: 22,
        GameSpecialOddsValue: '<Spov>1.5',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: 'Más 1.5',
        NodeId: '7248672526',
        ParentNodeId: '7248672430',
        Priority: 0,
        SportHandle: 'soccer',
        Locked: false,
      },
    ],
    DisplayTypeName: '2buttonline',
    CategoryInfo: {
      CategoryId: '60',
      CategoryName: 'GOLES',
      IsRelevant: false,
    },
    CategoryInfos: [
      {
        CategoryId: '60',
        CategoryName: 'GOLES',
        IsRelevant: false,
      },
      {
        CategoryId: '45',
        CategoryName: '1ª PARTE',
        IsRelevant: false,
      },
    ],
    GameType: 22,
    SmartMarketAvailable: false,
    Spov: '<Spov>1.5',
    Name: '1ª Parte - Más/Menos Total Goles',
    NodeId: '7248672430',
    ParentNodeId: '7248672410',
    Priority: 9822,
    SportHandle: 'soccer',
    Locked: false,
  },
  {
    Results: [
      {
        Odd: 1.85,
        SortOrder: 0,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '103843409',
        LocationId: '103844889',
        LeagueId: '1044751943',
        EventId: '7248672410',
        EventHasHandicap: false,
        GameId: '7248672434',
        GameTypeId: 38,
        GameSpecialOddsValue: '',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: 'Impar',
        NodeId: '7248672537',
        ParentNodeId: '7248672434',
        Priority: 0,
        SportHandle: 'soccer',
        Locked: false,
      },
      {
        Odd: 1.85,
        SortOrder: 1,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '103843409',
        LocationId: '103844889',
        LeagueId: '1044751943',
        EventId: '7248672410',
        EventHasHandicap: false,
        GameId: '7248672434',
        GameTypeId: 38,
        GameSpecialOddsValue: '',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: 'Par',
        NodeId: '7248672536',
        ParentNodeId: '7248672434',
        Priority: 1,
        SportHandle: 'soccer',
        Locked: false,
      },
    ],
    DisplayTypeName: '2buttonline',
    CategoryInfo: {
      CategoryId: '60',
      CategoryName: 'GOLES',
      IsRelevant: false,
    },
    CategoryInfos: [
      {
        CategoryId: '60',
        CategoryName: 'GOLES',
        IsRelevant: false,
      },
    ],
    GameType: 38,
    SmartMarketAvailable: false,
    Spov: '',
    Name: 'Par/Impar Total Goles',
    NodeId: '7248672434',
    ParentNodeId: '7248672410',
    Priority: 9660,
    SportHandle: 'soccer',
    Locked: false,
  },
  {
    Results: [
      {
        Odd: 3.4,
        SortOrder: 2,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '103843409',
        LocationId: '103844889',
        LeagueId: '1044751943',
        EventId: '7248672410',
        EventHasHandicap: false,
        GameId: '7248672418',
        GameTypeId: 40,
        GameSpecialOddsValue: '',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: 'Empate',
        NodeId: '7248672467',
        ParentNodeId: '7248672418',
        Priority: 2,
        SportHandle: 'soccer',
        Locked: false,
      },
      {
        Odd: 2.25,
        SortOrder: 0,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '103843409',
        LocationId: '103844889',
        LeagueId: '1044751943',
        EventId: '7248672410',
        EventHasHandicap: false,
        GameId: '7248672418',
        GameTypeId: 40,
        GameSpecialOddsValue: '',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: '1ª Parte',
        NodeId: '7248672468',
        ParentNodeId: '7248672418',
        Priority: 0,
        SportHandle: 'soccer',
        Locked: false,
      },
      {
        Odd: 2.625,
        SortOrder: 1,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '103843409',
        LocationId: '103844889',
        LeagueId: '1044751943',
        EventId: '7248672410',
        EventHasHandicap: false,
        GameId: '7248672418',
        GameTypeId: 40,
        GameSpecialOddsValue: '',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: '2ª Parte',
        NodeId: '7248672469',
        ParentNodeId: '7248672418',
        Priority: 1,
        SportHandle: 'soccer',
        Locked: false,
      },
    ],
    DisplayTypeName: '3buttonline',
    CategoryInfo: {
      CategoryId: '60',
      CategoryName: 'GOLES',
      IsRelevant: false,
    },
    CategoryInfos: [
      {
        CategoryId: '60',
        CategoryName: 'GOLES',
        IsRelevant: false,
      },
    ],
    GameType: 40,
    SmartMarketAvailable: false,
    Spov: '',
    Name: 'Parte con Más Goles',
    NodeId: '7248672418',
    ParentNodeId: '7248672410',
    Priority: 9730,
    SportHandle: 'soccer',
    Locked: false,
  },
  {
    Results: [
      {
        Odd: 10,
        SortOrder: 1,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '103843409',
        LocationId: '103844889',
        LeagueId: '1044751943',
        EventId: '7248672410',
        EventHasHandicap: false,
        GameId: '7248672423',
        GameTypeId: 21,
        GameSpecialOddsValue: '',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: '0 o 1 gol',
        NodeId: '7248672508',
        ParentNodeId: '7248672423',
        Priority: 1,
        SportHandle: 'soccer',
        Locked: false,
      },
      {
        Odd: 2.4,
        SortOrder: 8,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '103843409',
        LocationId: '103844889',
        LeagueId: '1044751943',
        EventId: '7248672410',
        EventHasHandicap: false,
        GameId: '7248672423',
        GameTypeId: 21,
        GameSpecialOddsValue: '',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: '4 o 5 goles',
        NodeId: '7248672510',
        ParentNodeId: '7248672423',
        Priority: 8,
        SportHandle: 'soccer',
        Locked: false,
      },
      {
        Odd: 2,
        SortOrder: 4,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '103843409',
        LocationId: '103844889',
        LeagueId: '1044751943',
        EventId: '7248672410',
        EventHasHandicap: false,
        GameId: '7248672423',
        GameTypeId: 21,
        GameSpecialOddsValue: '',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: '2 o 3 goles',
        NodeId: '7248672509',
        ParentNodeId: '7248672423',
        Priority: 4,
        SportHandle: 'soccer',
        Locked: false,
      },
      {
        Odd: 7,
        SortOrder: 13,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '103843409',
        LocationId: '103844889',
        LeagueId: '1044751943',
        EventId: '7248672410',
        EventHasHandicap: false,
        GameId: '7248672423',
        GameTypeId: 21,
        GameSpecialOddsValue: '',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: '6 o más',
        NodeId: '7248672511',
        ParentNodeId: '7248672423',
        Priority: 13,
        SportHandle: 'soccer',
        Locked: false,
      },
    ],
    DisplayTypeName: '2buttonlist',
    CategoryInfo: {
      CategoryId: '60',
      CategoryName: 'GOLES',
      IsRelevant: false,
    },
    CategoryInfos: [
      {
        CategoryId: '60',
        CategoryName: 'GOLES',
        IsRelevant: false,
      },
    ],
    GameType: 21,
    SmartMarketAvailable: false,
    Spov: '',
    Name: 'Total de Goles',
    NodeId: '7248672423',
    ParentNodeId: '7248672410',
    Priority: 0,
    SportHandle: 'soccer',
    Locked: false,
  },
];
export const locked = false;
