export const games = [
  {
    Results: [
      {
        Odd: 3.05,
        SortOrder: 0,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '2819846742',
        LocationId: '3026921343',
        LeagueId: '4305980847',
        EventId: '6862306720',
        EventHasHandicap: false,
        GameId: '6863759224',
        GameTypeId: 97,
        GameSpecialOddsValue: '',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: 'Alexander Bublik',
        NodeId: '6863759241',
        ParentNodeId: '6863759224',
        Priority: 0,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Odd: 1.37,
        SortOrder: 1,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '2819846742',
        LocationId: '3026921343',
        LeagueId: '4305980847',
        EventId: '6862306720',
        EventHasHandicap: false,
        GameId: '6863759224',
        GameTypeId: 97,
        GameSpecialOddsValue: '',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: 'Tung-Lin Wu',
        NodeId: '6863759240',
        ParentNodeId: '6863759224',
        Priority: 1,
        SportHandle: 'tennis',
        Locked: false,
      },
    ],
    DisplayTypeName: '2buttonline',
    CategoryInfo: {
      CategoryId: '99',
      CategoryName: 'PRINCIPALES',
      IsRelevant: true,
    },
    CategoryInfos: [
      {
        CategoryId: '99',
        CategoryName: 'PRINCIPALES',
        IsRelevant: true,
      },
    ],
    GameType: 97,
    SmartMarketAvailable: false,
    Spov: '',
    Name: 'Ganador del partido',
    NodeId: '6863759224',
    ParentNodeId: '6862306720',
    Priority: 9500,
    SportHandle: 'tennis',
    Locked: false,
  },
  {
    Results: [
      {
        Odd: 1.8,
        SortOrder: 0,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '2819846742',
        LocationId: '3026921343',
        LeagueId: '4305980847',
        EventId: '6862306720',
        EventHasHandicap: false,
        GameId: '6863971046',
        GameTypeId: 195,
        GameSpecialOddsValue: '<Spov>22.5',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: 'Más 22.5',
        NodeId: '6863971047',
        ParentNodeId: '6863971046',
        Priority: 0,
        SportHandle: 'tennis',
        Locked: false,
      },
      {
        Odd: 1.9,
        SortOrder: 1,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '2819846742',
        LocationId: '3026921343',
        LeagueId: '4305980847',
        EventId: '6862306720',
        EventHasHandicap: false,
        GameId: '6863971046',
        GameTypeId: 195,
        GameSpecialOddsValue: '<Spov>22.5',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: 'Menos 22.5',
        NodeId: '6863971048',
        ParentNodeId: '6863971046',
        Priority: 1,
        SportHandle: 'tennis',
        Locked: false,
      },
    ],
    DisplayTypeName: '2buttonline',
    CategoryInfo: {
      CategoryId: '99',
      CategoryName: 'PRINCIPALES',
      IsRelevant: true,
    },
    CategoryInfos: [
      {
        CategoryId: '99',
        CategoryName: 'PRINCIPALES',
        IsRelevant: true,
      },
    ],
    GameType: 195,
    SmartMarketAvailable: false,
    Spov: '<Spov>22.5',
    Name: 'Total de Juegos Más/Menos',
    NodeId: '6863971046',
    ParentNodeId: '6862306720',
    Priority: 9450,
    SportHandle: 'tennis',
    Locked: false,
  },
  {
    Results: [
      {
        Odd: 3,
        SortOrder: 0,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '2817453298',
        LocationId: '2817453310',
        LeagueId: '3009130476',
        EventId: '6744932314',
        EventHasHandicap: false,
        GameId: '6744932361',
        GameTypeId: 1,
        GameSpecialOddsValue: '',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: 'Altona Magic SC',
        NodeId: '6744932382',
        ParentNodeId: '6744932361',
        Priority: 0,
        SportHandle: 'soccer',
        Locked: false,
      },
      {
        Odd: 2.75,
        SortOrder: 1,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '2817453298',
        LocationId: '2817453310',
        LeagueId: '3009130476',
        EventId: '6744932314',
        EventHasHandicap: false,
        GameId: '6744932361',
        GameTypeId: 1,
        GameSpecialOddsValue: '',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: 'X',
        NodeId: '6744932383',
        ParentNodeId: '6744932361',
        Priority: 1,
        SportHandle: 'soccer',
        Locked: false,
      },
      {
        Odd: 2.4,
        SortOrder: 2,
        IsLive: true,
        upOdd: false,
        downOdd: false,
        IsNonRunner: false,
        SportId: '2817453298',
        LocationId: '2817453310',
        LeagueId: '3009130476',
        EventId: '6744932314',
        EventHasHandicap: false,
        GameId: '6744932361',
        GameTypeId: 1,
        GameSpecialOddsValue: '',
        GameBetTypeAvailability: 0,
        GameNumberOfStarters: 0,
        Name: 'Hume City',
        NodeId: '6744932384',
        ParentNodeId: '6744932361',
        Priority: 2,
        SportHandle: 'soccer',
        Locked: false,
      },
    ],
    DisplayTypeName: '3way',
    CategoryInfo: {
      CategoryId: '99',
      CategoryName: 'PRINCIPALES',
      IsRelevant: true,
    },
    CategoryInfos: [
      {
        CategoryId: '99',
        CategoryName: 'PRINCIPALES',
        IsRelevant: true,
      },
    ],
    GameType: 1,
    SmartMarketAvailable: true,
    Spov: '',
    Name: '1X2',
    NodeId: '6744932361',
    ParentNodeId: '6744932314',
    Priority: 9990,
    SportHandle: 'soccer',
    Locked: false,
  },
];
/**
 * calculates the margin of the sportBook (codere) for an array of possible results
 * @param games the games the margin is going to be calculated from
 * @param name the name of the market
 * @returns an object containing the name of the market and its margin
 */
const marginCalculator = (games: Array<number>, name: string) => {
  // eslint-disable-next-line prefer-const
  let marginOfEvents = {
    [name]: {},
  };
  //debugger;
  games.map((gamesEl: any) => {
    // eslint-disable-next-line prefer-const
    let divisionResults: Array<number> = [];

    gamesEl.Results.map((el: any) => {
      const division = 1 / el.Odd;
      divisionResults.push(division);
    });
    if (divisionResults.length === 0) return 'Margin calculator did not work';
    const result = divisionResults.reduce((acc: number, curr: number) => acc + curr).toFixed(2);
    marginOfEvents[name] = {
      [gamesEl.Name]: result + ' %',
    };
  });
  return marginOfEvents;
};
export default marginCalculator;
